serve:
  addr: ":8080" #运行的端口
  readTimeout: 5s #读超时
  writeTimeout: 5s #写超时
  defaultTimeout: 30s #优雅退出时的默认时间
mysql:
  user: "root"
  password: "zxz123456"
  host: "127.0.0.1"
  port: 3306
  dbname: "mall"
redis:
  addr: "192.168.28.16:6379"
  password: ""
  poolSize: 20
  CacheTime: 1h
SMTPInfo:
  host: "smtp.qq.com"
  port: 465
  userName: "1197285120@qq.com"
  password: "***" #密码
  isSSL: true
  from: "1197285120@qq.com" #发件人
  to: #接收人
    - "1197285120@qq.com"
Log: # 日志配置文件
  Level: debug
  LogSavePath: "storage/Applogs/" # 日志保存路径
  HighLevelFile: error          # 高级别日志文件名
  LowLevelFile: info          # 低级别文件名
  LogFileExt: .log          # 日志文件后缀
  MaxSize: 10 # 日志文件最大大小
  MaxAge: 30 # 日志文件最大保存天数
  MaxBackups: 7 # 最大备份数
  Compress: false # 是否压缩
Captcha:
  width: 80 #宽度
  height: 240 #高度
  length: 5
  maxSkew: 0.7
  dotCount: 80
  expired: 30 #过期时间
Limit:
  IPLimit: # IP限流
    Cap: 10           # 令牌桶容量
    GenNum: 5         # 令牌产生数
    GenTime: 1       # 令牌产生时间
    Cost: 1           # 本次取走的令牌数
  APILimit: # API限流
    Email:
      - Count: 5
        Duration: 1s
        Burst: 5
      - Count: 30
        Duration: 1m
        Burst: 5
    Upload:
      - Count: 1
        Duration: 1s
        Burst: 1
Worker: # 工作池配置
  TaskChanCapacity: 50 # 任务队列容量
  WorkerChanCapacity: 50 # 工作队列容量
  WorkerNum: 10 # 工作池数量
Token:
  Key: "wJZ8a507mbp3HZiJzUL0aUBo3WDlvmbp"
  AccessTokenExpire: 15h
  RefreshTokenExpire: 20h
  AuthType: "x-token"
  AuthKey: "Claims"
OSS:
  Endpoint: "http://oss-cn-hangzhou.aliyuncs.com"
  AccessKeyId: "LTAI5t5geL57b9nZyXcyH3pW"
  AccessKeySecret: "w6FpPuAiuPCv1d9Ij3KB0QCmOlw1my"
  BucketName: "lycmall2"
  BasePath: "mall"
  BucketUrl: "http://lycmall2.oss-cn-hangzhou.aliyuncs.com"
Auto:
  SendEmailTime: 60s
  CodeValidTime: 1h
EsInfo:
  Host: "192.168.28.16"
  Port: 9200
Alipay:
  AppID: "2021000122617027"
  PrivateKey: "***"
  AliPublicKey: "***"
  NotifyURL: http://yyy.freehk.svipss.top/api/v1/pay/alipay/notify
  ReturnURL: "http://127.0.0.1:8090/return"
  ProductCode: "FAST_INSTANT_TRADE_PAY"
  IsProduction: false